/**
* test Mobile
* Mobile API for test
*
* 
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package samkazmi.example.datainterfaces.models


data class Business (
        val id: Int,
        val title: String,
        val address: String,
        val lat: String,
        val lng: String,
        val distance : Double? =null,
        val duration : Double? = null,
        val businessType: BusinessType? = null,
        val phone: String? = null,
        val businessHours: Schedule? = null,
        val amenities: Array<String>? = null,
        val banner: Document? = null
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as Business

        if (id != other.id) return false
        if (title != other.title) return false
        if (address != other.address) return false
        if (lat != other.lat) return false
        if (lng != other.lng) return false
        if (businessType != other.businessType) return false
        if (phone != other.phone) return false
        if (businessHours != other.businessHours) return false
        if (amenities != null) {
            if (other.amenities == null) return false
            if (!amenities.contentEquals(other.amenities)) return false
        } else if (other.amenities != null) return false
        if (banner != other.banner) return false

        return true
    }

    override fun hashCode(): Int {
        var result = id
        result = 31 * result + title.hashCode()
        result = 31 * result + address.hashCode()
        result = 31 * result + lat.hashCode()
        result = 31 * result + lng.hashCode()
        result = 31 * result + (businessType?.hashCode() ?: 0)
        result = 31 * result + (phone?.hashCode() ?: 0)
        result = 31 * result + (businessHours?.hashCode() ?: 0)
        result = 31 * result + (amenities?.contentHashCode() ?: 0)
        result = 31 * result + (banner?.hashCode() ?: 0)
        return result
    }

}


