/**
* test Mobile
* Mobile API for test
*
* 
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package samkazmi.example.datainterfaces.models


/**
 *  
 * @param id  
 * @param icon  
 * @param name */
data class BusinessType (
    val id: Int,
    val name: String,
    val icon: Document? = null
) {

}


