/**
* Test Mobile
* Mobile API for test
*
* 
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package samkazmi.example.datainterfaces.models

import org.joda.time.DateTime


/**
 *  
 * @param id  
 * @param url  
 * @param createdAt */
data class Document (
    val id: Int,
    val url: String,
    val createdAt: DateTime
) {

}


