/**
 * NeedCharge Mobile
 * Mobile API for needcharge
 *
 *
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package samkazmi.example.datainterfaces.models

import org.joda.time.DateTime


/**
 *
 * @param id
 * @param day 0 => Monday 1 => Tuesday 2 => Wednesday 3 => Thursday 4 => Friday 5 => Saturday 6 => Sunday
 * @param startTime
 * @param endTime */
data class Schedule(
        val id: Int,
        /* 0 => Monday 1 => Tuesday 2 => Wednesday 3 => Thursday 4 => Friday 5 => Saturday 6 => Sunday */

        val day: Int,
        val startTime: DateTime,
        val endTime: DateTime
) {

}


